#cloud-config
datasource:
  Ec2:
    strict_id: false
write_files:
- content: |
    net.ipv6.conf.all.disable_ipv6=1
    net.ipv6.conf.default.disable_ipv6=1
  path: /etc/sysctl.d/88-disable.conf
  owner: root
users:
  - default
  - name: yc-user
    groups: wheel
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "${ssh_key}"
packages:
  - netplan.io
  - openssh-server
package_update: true
package_reboot_if_required: true
runcmd:
  - sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sysctl -w net.ipv6.conf.default.disable_ipv6=1
